[tool.autopep8]
max_line_length = 60
in-place = true
recursive = true
aggressive = 3

[tool.black]
line-length = 60
target-version = ['py310']

[tool.isort]
profile = "black"
multi_line_output = 3
force_grid_wrap = 0
line_length = 60
