[tool.autopep8]
max_line_length = 60
in-place = true
recursive = true
aggressive = 3

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 60