[tool.autopep8]
max_line_length = 80
in-place = true
recursive = true
aggressive = 3

[tool.black]
line-length = 80
target-version = ['py311']

[tool.isort]
profile = "black"
force_grid_wrap = 0
line_length = 80
